version: "3.7"

services:
  app:
    image: alswl/excalidraw:v0.17.3-fork-b1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=http://localhost:3001/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=http://localhost:3001/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=http://localhost:3002/
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=http://localhost:3001/api/v2
      - VITE_APP_STORAGE_BACKEND=http
      - VITE_APP_DISABLE_TRACKING=true
      - PUBLIC_URL=http://localhost:3000

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3001:8080"
    environment:
      - STORAGE_URI=mongodb://admin:password123@mongodb:27017
    networks:
      - draw-internal

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3002:80"

  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - draw-internal

  mongoexpress:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - draw-internal

networks:
  draw-internal:
    external: false
